
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'mbIsW\xf0\xeeM\xba\xee\x94\x8c\xe6\xdcn\x05'
    
_lr_action_items = {'WORD':([20,21,24,26,28,30,34,],[30,31,32,33,34,35,36,]),'PROTOCOL':([0,3,14,17,18,19,22,23,25,29,],[13,-9,13,-7,-8,-5,-3,-4,-10,-6,]),'DBL_HYPHEN':([0,3,14,17,18,19,22,23,25,29,],[5,-9,5,-7,-8,-5,-3,-4,-10,-6,]),'IP_DST':([0,3,14,17,18,19,22,23,25,29,],[6,-9,6,-7,-8,-5,-3,-4,-10,-6,]),'PORT_DST':([0,3,14,17,18,19,22,23,25,29,],[8,-9,8,-7,-8,-5,-3,-4,-10,-6,]),'COLON':([6,8,11,13,15,],[20,21,24,26,28,]),'PORT_SRC':([0,3,14,17,18,19,22,23,25,29,],[11,-9,11,-7,-8,-5,-3,-4,-10,-6,]),'error':([0,3,14,17,18,19,22,23,25,29,],[12,-9,12,-7,-8,-5,-3,-4,-10,-6,]),'NL':([0,1,2,3,4,5,9,10,12,14,16,17,18,19,22,23,25,29,30,31,32,33,34,35,36,],[3,17,18,-9,19,-11,22,23,25,3,29,-7,-8,-5,-3,-4,-10,-6,-16,-18,-17,-12,-14,-15,-13,]),'IP_SRC':([0,3,14,17,18,19,22,23,25,29,],[15,-9,15,-7,-8,-5,-3,-4,-10,-6,]),'$end':([3,7,14,17,18,19,22,23,25,27,29,],[-9,0,-1,-7,-8,-5,-3,-4,-10,-2,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'port_src_line':([0,14,],[1,1,]),'port_dst_line':([0,14,],[2,2,]),'ip_src_line':([0,14,],[4,4,]),'lines':([0,14,],[7,27,]),'hyphen_line':([0,14,],[9,9,]),'protocol_line':([0,14,],[10,10,]),'line':([0,14,],[14,14,]),'ip_dst_line':([0,14,],[16,16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lines","S'",1,None,None,None),
  ('lines -> line','lines',1,'p_lines','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',32),
  ('lines -> line lines','lines',2,'p_lines','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',33),
  ('line -> hyphen_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',37),
  ('line -> protocol_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',38),
  ('line -> ip_src_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',39),
  ('line -> ip_dst_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',40),
  ('line -> port_src_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',41),
  ('line -> port_dst_line NL','line',2,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',42),
  ('line -> NL','line',1,'p_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',43),
  ('line -> error NL','line',2,'p_line_error','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',47),
  ('hyphen_line -> DBL_HYPHEN','hyphen_line',1,'p_hyphen_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',51),
  ('protocol_line -> PROTOCOL COLON WORD','protocol_line',3,'p_protocol_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',57),
  ('ip_src_line -> IP_SRC COLON WORD WORD','ip_src_line',4,'p_ip_src_line_1','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',62),
  ('ip_src_line -> IP_SRC COLON WORD','ip_src_line',3,'p_ip_src_line_2','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',67),
  ('ip_dst_line -> IP_DST COLON WORD WORD','ip_dst_line',4,'p_ip_dst_line_1','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',72),
  ('ip_dst_line -> IP_DST COLON WORD','ip_dst_line',3,'p_ip_dst_line_2','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',77),
  ('port_src_line -> PORT_SRC COLON WORD','port_src_line',3,'p_port_src_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',82),
  ('port_dst_line -> PORT_DST COLON WORD','port_dst_line',3,'p_port_dst_line','/root/Documents/springbok/Parser/QueryPathParser/QueryPathYacc.py',87),
]
